name: Sync Git Folder

concurrency: prod_environment

on:
  push:
    branches:
      - main

permissions:
  contents: read
  # id-token not needed for PAT auth

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'Update git folder'
    environment: Prod
    env:
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@v0.271.0

      - name: Update git folder
        run: |
          databricks repos update /Workspace/Shared/FinanceDatabricks --branch main
